chore(new): added new workflows

diff --git a/.github/workflows/update-confluence.yml b/.github/workflows/update-confluence.yml
--- a/.github/workflows/update-confluence.yml
+++ b/.github/workflows/update-confluence.yml
@@ -53,10 +53,16 @@ jobs:
 
           echo "API Response: $RESPONSE"
 
+          if echo "$RESPONSE" | grep -q "Unauthorized"; then
+            echo "Authentication failed! Check your API token and username."
+            exit 1
+          fi
+
           PAGE_VERSION=$(echo "$RESPONSE" | jq -r '.version.number // 1')
           echo "Current Page Version: $PAGE_VERSION"
 
           echo "PAGE_VERSION=$PAGE_VERSION" >> $GITHUB_ENV
+
 
       - name: Update Confluence Page
         run: |
